### ISSUE TITLE
能否中ReadMe中写明下兼容nodejs的版本？

### ISSUE THREAD

**Issue by fun90** [master-coder-ll/v2ray-manager-console#7]

**Comment by master-coder-ll** [comment]
node v16.9.1 ,   [node_modules](https://gitee.com/wubie/vue2-element-admin-simplify/raw/master/%5Bbackup%5Dnode_modules.zip)

**Comment by fun90** [comment]
谢谢
用你的新版依赖，折腾一天没弄好
用上古时期的版本，稍微修改下居然可以了
我的版本：node 16.20

https://github.com/fun90/xray-admin
